name: Deploy SAM App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: sam build --template-file Lambda_functions/template.yaml

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file Lambda_functions/template.yaml \
            --stack-name insurance-agentic-demo \
            --s3-bucket ${{ secrets.AWS_SAM_ARTIFACT_BUCKET }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              BucketName=${{ secrets.AWS_S3_BUCKET_NAME }} \
              ClaimsPrefix=${{ secrets.AWS_CLAIMS_DATA }} \
              InsuranceDataPrefix=${{ secrets.AWS_INSURANCE_DATA }} \
              AwsRegion=${{ secrets.AWS_REGION }} \
              BedrockPrimaryModel=${{ secrets.AWS_BEDROCK_PRIMARY_MODEL }} \
              BedrockFallbackModel=${{ secrets.AWS_BEDROCK_FALLBACK_MODEL }} \
              BedrockRouterModel=${{ secrets.AWS_BEDROCK_ROUTER_MODEL }} \
              BedrockSynthModel=${{ secrets.AWS_BEDROCK_SYNTH_MODEL }} \
              GetPolicyFunction=${{ secrets.GET_POLICY_FUNCTION }} \
              CheckDocFunction=${{ secrets.CHECK_DOC_FUNCTION }} \
              GetClaimFunction=${{ secrets.GET_CLAIM_FUNCTION }} \
              ConversationTable=${{ secrets.CONVERSATION_TABLE }}